on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: felipevolpone/action-maestro-cloud@v0.6
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: .github/app-debug.apk
          api-url: https://api.smobile.dev
          android-api-level: 33
          async: true
