on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - uses: mobile-dev-inc/action-maestro-cloud@add-android-api-level
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: .github/app-debug.apk
          api-url: https://api.smobile.dev
          android-api-level: 33
          async: true