on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - id: first
        uses: igorsmotto/action-maestro-cloud@v0.5-beta
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: CovidCertificateVerifier.app
          api-url: https://api.smobile.dev
          timeout: 1
