on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: mobile-dev-inc/action-maestro-cloud@94a07ca79a253059a75813a22b7463a0c2277e3f
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: .github/app-debug.apk
          api-url: https://api.smobile.dev
          android-api-level: 33
          workspace: .github/maestro/
          async: true
