on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Switch to Xcode 13
        run: sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      
      - uses: igorsmotto/action-maestro-cloud@v0.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: CovidCertificateVerifier.app
          api-url: https://api.smobile.dev
          async: true
