on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Switch to Xcode 13
        run: sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      
      - run: fastlane gym --scheme "Release-Verifier-Prod" --skip_package_ipa true --disable_package_automatic_updates true --destination "generic/platform=iOS Simulator" --archive_path build
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build.xcarchive/Products/Applications/CovidCertificateVerifier.app
          api-url: https://api.smobile.dev
